# 🛠️ Development docker-compose
version: '3.8'

services:
  # 🤖 Budget Bot (Development)
  budget-bot-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: base  # Используем базовый stage для разработки
    container_name: budget-bot-dev
    restart: "no"  # Не перезапускать автоматически в dev
    environment:
      - DATABASE_URL=sqlite:////app/data/budget_bot_dev.db
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=development
      - DEBUG=1
    env_file:
      - .env.local
    volumes:
      - .:/app  # Монтируем весь проект для hot reload
      - dev_data:/app/data
      - ./logs:/app/logs
    networks:
      - budget-dev-network
    command: python bot.py
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "python", "-c", "import sqlite3; sqlite3.connect('/app/data/budget_bot_dev.db').execute('SELECT 1')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 🗄️ PostgreSQL (для тестирования)
  postgres-dev:
    image: postgres:15-alpine
    container_name: budget-postgres-dev
    restart: "no"
    environment:
      POSTGRES_DB: budget_bot_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - budget-dev-network
    ports:
      - "5433:5432"  # Другой порт для dev

  # 🟥 Redis (для тестирования кеширования)
  redis-dev:
    image: redis:7-alpine
    container_name: budget-redis-dev
    restart: "no"
    command: redis-server --requirepass dev_password
    volumes:
      - redis_dev_data:/data
    networks:
      - budget-dev-network
    ports:
      - "6380:6379"  # Другой порт для dev

  # 📧 MailHog (для тестирования email уведомлений)
  mailhog:
    image: mailhog/mailhog:latest
    container_name: budget-mailhog
    restart: "no"
    networks:
      - budget-dev-network
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI

  # 🧪 Test runner
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: budget-test-runner
    environment:
      - DATABASE_URL=sqlite:///tmp/test.db
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    networks:
      - budget-dev-network
    command: python -m pytest tests/ -v
    profiles:
      - testing

networks:
  budget-dev-network:
    driver: bridge

volumes:
  dev_data:
    driver: local
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local